---
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: "https://github.com/adrienverge/yamllint.git"
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ['--strict', '-d', '{extends: default, rules: {line-length: {max: 120}}}']
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: v1.19.1
    hooks:
      - id: mypy
        additional_dependencies: [types-dateparser, types-mock, types-tabulate]
  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: v0.4.2
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: "https://github.com/igorshubovych/markdownlint-cli"
    rev: v0.47.0
    hooks:
      - id: markdownlint-fix
