repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: v0.9.5
    hooks:
    -   id: trailing-whitespace
        language_version: python3.6
    -   id: end-of-file-fixer
        language_version: python3.6
        exclude: ^\.activate\.sh$
    -   id: autopep8-wrapper
        language_version: python3.6
        args: [-i, --max-line-length=121]
    -   id: check-yaml
        language_version: python3.6
    -   id: debug-statements
        language_version: python3.6
    -   id: name-tests-test
        language_version: python3.6
    -   id: flake8
        language_version: python3.6
        exclude: ^docs/.*
-   repo: git@github.com:asottile/reorder_python_imports
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python3.6
