repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: v0.9.5
    hooks:
    -   id: trailing-whitespace
        language_version: python3.6
    -   id: end-of-file-fixer
        language_version: python3.6
        exclude: ^\.activate\.sh$
    -   id: check-yaml
        language_version: python3.6
    -   id: debug-statements
        language_version: python3.6
    -   id: name-tests-test
        language_version: python3.6
    -   id: flake8
        language_version: python3.6
        exclude: ^docs/.*
-   repo: git@github.com:asottile/reorder_python_imports
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python3.6
-   repo: git@github.com:pre-commit/mirrors-autopep8
    sha: v1.4.4
    hooks:
    -   id: autopep8
        language_version: python3.6
        args: [-i, --ignore, "E226,E24,W50,W690,E702,E703"]
