repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v0.9.5
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: flake8
        exclude: ^docs/.*
-   repo: git@github.com:asottile/reorder_python_imports
    rev: v0.3.5
    hooks:
    -   id: reorder-python-imports
-   repo: git@github.com:pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8
        args: [-i, --ignore, "E226,E24,W50,W690,E702,E703"]
